version: '3.7'

services:
  metabase:
    image: metabase/metabase:v0.44.6
    container_name: metabase
    ports:
      - "3000:3000"
    volumes:
      - ./plugins/ch.jar:/plugins/clickhouse.jar
      - metabase_data:/metabase-data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./ch_data:/var/lib/clickhouse/
      - ./ch_logs:/var/log/clickhouse-server/
        #      - ./ch_conf/users.xml:/etc/clickhouse-server/users.xml
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"

volumes:
  metabase_data:
    driver: local

