version: '3.9'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 3010:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: 10.130.4.60
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
      #  postgres:
      #    image: postgres:latest
      #    container_name: postgres
      #    hostname: postgres
      #    environment:
      #      POSTGRES_USER: metabase
      #      POSTGRES_DB: metabaseappdb
      #      POSTGRES_PASSWORD: mysecretpassword
      #    networks:
      #      - metanet1
networks:
  metanet1:
    driver: bridge

