version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "8080:8080"  # Expose the status endpoint
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Make sure to provide your nginx.conf file
    networks:
      - nginx_network

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    ports:
      - "9113:9113"
    environment:
      - NGINX_SCRAPE_URI=http://nginx:8080/nginx_status  # Link to Nginx's stub_status endpoint
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

