variables:
  CI_REPOSITORY_URL: "https://your-remote-repository-url.git"
  CI_COMMIT_USER_EMAIL: "your-email@example.com"
  CI_COMMIT_USER_NAME: "CI/CD Pipeline"

stages:
  - update        # List of stages for jobs, and their order of execution
  - build

update_all_submodules:
  stage: update
  script:
    # Step 1: Initialize and update all submodules
    - git submodule update --init --recursive
    - git submodule update --remote --recursive

    # Step 2: Configure Git and commit changes
    - git config --global user.email "$CI_COMMIT_USER_EMAIL"  # Set the Git config for commit
    - git config --global user.name "$CI_COMMIT_USER_NAME"
    - git remote set-url origin "$CI_REPOSITORY_URL"  # Ensure the correct remote URL is set
    - |
      if [[ $(git status --porcelain) ]]; then
        echo "Submodules have updates. Preparing to commit...";
        git add .gitmodules;  # Add the .gitmodules file if it changed
        git add .;  # Stage changes (updates in submodule references)
        git commit -m "CI Update all submodules to the latest versions";  # Commit changes
        git push origin HEAD:master;  # Push changes back to the main project
      else
        echo "No updates in submodules.";
      fi
