version: "3"

services:

  # WireGuard VPN service
  wireguard:
    image: linuxserver/wireguard:1.0.20210914-r4-ls39
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
    ports:
      # Port for WireGuard-UI
      # Port of the WireGuard VPN server
      - "51820:51820/udp"
    networks:
      - wg-net

  # WireGuard-UI service
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:0.6.1
    container_name: wireguard-ui
    ports:
       - "5000:5000"
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    # Use the network of the 'wireguard' service
    # This enables to show active clients in the status page
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=password
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - ./config:/etc/wireguard
    networks:
      - wg-net

networks:
  wg-net:

