version: '2.1'
services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    volumes:
      - ./mc-redis-demo:/data
    command: redis-server --save 60 1 --loglevel warning --requirepass 1397.B@sa
    ports:
      - "6379:6379"

